//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Nswitch/Scripts/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Vehicle"",
            ""id"": ""ab715d13-5a7c-4c02-bbe9-d67789670936"",
            ""actions"": [
                {
                    ""name"": ""Forward"",
                    ""type"": ""Value"",
                    ""id"": ""dae99c11-a7ad-47f7-aeea-a13ef9cebeac"",
                    ""expectedControlType"": ""Double"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Reverse"",
                    ""type"": ""Button"",
                    ""id"": ""835585e9-18e9-4761-89d6-eae82a2ff2da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Steering"",
                    ""type"": ""Value"",
                    ""id"": ""ab4e497e-5eb5-43aa-af5d-a39129424aca"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Handbrake"",
                    ""type"": ""Value"",
                    ""id"": ""6a36b7cb-af2b-476b-801a-b3dc5873a102"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""WeaponAim"",
                    ""type"": ""Value"",
                    ""id"": ""013d3460-3423-4d97-908a-cd4e61505d2d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Boost"",
                    ""type"": ""Value"",
                    ""id"": ""21884104-a165-40eb-983b-9a3dae9781a7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""6ace29f0-01ba-4dbc-8971-f5d07e46ae95"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialAction"",
                    ""type"": ""Button"",
                    ""id"": ""d51d0da4-70c9-45c8-b943-0f76beedcdcf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbsoluteControl"",
                    ""type"": ""Value"",
                    ""id"": ""04308684-5af2-4843-9d7f-0b345b736999"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ToggleAutoAim"",
                    ""type"": ""Button"",
                    ""id"": ""fc4d2172-7577-4216-a1e0-e9686ee5d827"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AnyButton"",
                    ""type"": ""Button"",
                    ""id"": ""c3a43d7b-5e82-4457-bba2-397396300ee6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""733c2b16-df72-418c-915e-3f701ced0dd9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4443e878-cfe7-4313-b145-1de76906fabb"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5025b1a2-ed8c-4871-ba5f-c400fbaa8e78"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48a24528-3f76-4689-ab16-33076ad43f24"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""Reverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8928d6aa-83ee-496f-8421-ff3034ab4f67"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Reverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d18c091f-b90f-4c2d-bf27-1b6eb4690723"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""LRArrows"",
                    ""id"": ""d97c22f3-65b6-40e7-aebd-1f96cada7b0b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""3f3faf71-a30f-4e54-9066-3e01449db359"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a9360a45-dffe-4b0d-90d2-942c8a17940a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""623aeb16-9535-4307-9885-5a91c06a8234"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8076d900-e825-43b9-845f-dc0ed58f8cbd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""fd6d2579-07c7-4b55-933c-d99870d864f5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftJoystick"",
                    ""id"": ""a6ebe928-e522-4a39-99d1-a435de3f4cf2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""19aa62d2-6483-4d5e-b016-b488c1f2240e"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ac3cf7db-bcf4-43eb-a0bc-5dc95090e57e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""DPad"",
                    ""id"": ""94846632-778b-4fe4-a2b2-25ed0831d554"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0565b025-1302-4ac2-9ee4-bb2aaeb6cfba"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""661a60bc-aa00-457c-adab-b6180bf19571"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a7b2bcdf-64c3-4003-b0ee-f320d1f38681"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""Handbrake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9f1b0c3-64e4-4440-9129-3df3aff84268"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Handbrake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b50b6e2-b913-499c-adf2-649e6347e96e"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""WeaponAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30b0f002-9122-4fe0-b8b9-79eeb0ca782b"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""WeaponAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fc3324a-936c-41ba-828b-a51fa6620448"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59d294b3-a85f-41e8-a4e4-7cbd5e3a5211"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da836373-0aab-47bd-be11-4411d113468f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c22d3ced-636c-43f7-a4b1-4dd9323c33c1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b66b2d6-2f19-42ea-8b4b-604c5fd6a030"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88be9aa4-c56b-4266-90cb-ca2d435e1e61"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a4026a2-7995-4897-904b-5085b9ea4c69"",
                    ""path"": ""<DualShockGamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16f04b4d-ec0d-4808-8679-e97fa6a349e5"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b783e70f-cea4-44ff-973f-e2ecbbf7669b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""SpecialAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8eb5c226-4cfa-4b0b-b0a2-a9a4f3d2ef1c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SpecialAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""bb1f716f-137f-44d4-95ef-f077c859aba3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbsoluteControl"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""63d7c0b7-9ce1-4393-9236-c03fbce7e66a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""AbsoluteControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5a4e3c35-9e2d-4ce9-9c87-d02e97806717"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""AbsoluteControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""15a48e9a-c443-4daa-bab2-edf4047477f6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""AbsoluteControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0cdd6658-b493-44cd-8d02-e2b38b132156"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""AbsoluteControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""63ac0aab-4a5a-4b2d-8c0e-2766598e931f"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AbsoluteControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""DPad"",
                    ""id"": ""6ad20182-0c73-4770-a76d-15125c6a6149"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbsoluteControl"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c40fa743-dcb5-4b64-a48b-2e1fcdc6e9a2"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AbsoluteControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bad6836e-9bd0-455f-9bef-d36be4d26909"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AbsoluteControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""58c8f6cf-588d-4708-8d25-04f3bbdd5393"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AbsoluteControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fe521120-4e22-4f40-8ba9-54d79b9347e9"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AbsoluteControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""54a0b275-6b3a-4774-8902-12632c8c844e"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8909e5d8-6907-4518-8118-2dcc3b3ff5c0"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dde0a5fa-124d-4f6e-8d3d-60c99394a165"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1182885-ecb8-4d95-9978-0161c59846d1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""715c9a3c-6fa4-4cd8-bd36-c51df7137186"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78e4ae17-4022-420c-bed7-1b90f56452d7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e652c852-eb7c-4df0-b1b4-8f590f7c21b7"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc1ea90d-d331-40ef-abab-6a03cc39349f"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efd85bfe-3405-4c22-9d1b-91db9f02753d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""AnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2293ffe4-c0bf-4c79-bb26-e7967a54dadd"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""ToggleAutoAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fdc729e-f336-40c1-8999-cbbfc5d3264c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ToggleAutoAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""06b5cf90-5fab-43a4-80c3-fc6193127ed7"",
            ""actions"": [
                {
                    ""name"": ""NavigationUp"",
                    ""type"": ""Button"",
                    ""id"": ""15fe6705-e06d-4e6e-8ddb-fc62284a24a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigationDown"",
                    ""type"": ""Button"",
                    ""id"": ""dc49dcda-9413-4404-bb6d-ee1e30ab7877"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigationLeft"",
                    ""type"": ""Button"",
                    ""id"": ""17934a60-4fc1-4d31-9acd-b3c51270b33e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigationRight"",
                    ""type"": ""Button"",
                    ""id"": ""c4ace96b-5f41-4013-92d1-c3085816f81a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigationPrevious"",
                    ""type"": ""Button"",
                    ""id"": ""4282fe73-0715-4e33-b087-2bee7e20fe41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigationNext"",
                    ""type"": ""Button"",
                    ""id"": ""3c08ad55-62a4-49d5-99df-0fe253666fc0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigationTab"",
                    ""type"": ""Button"",
                    ""id"": ""e334113f-5b32-4870-903c-59213c64c4b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigationRightBumper"",
                    ""type"": ""Button"",
                    ""id"": ""8e8ab147-a852-4862-b5a5-f811895c22db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigationLeftBumper"",
                    ""type"": ""Button"",
                    ""id"": ""97d6388b-3292-4fb6-916e-a93fec2f5eab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseAction"",
                    ""type"": ""Button"",
                    ""id"": ""fda5cc6d-cb9d-4ebc-a1b1-0df971e9a63e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigationNextMouse"",
                    ""type"": ""Button"",
                    ""id"": ""26ab5111-f1d8-4245-8a95-4ea36ed4f4ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigationPreviousMouse"",
                    ""type"": ""Button"",
                    ""id"": ""f983f54a-4ae2-4acc-9699-2021cc96aabe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigationLeftMouse"",
                    ""type"": ""Button"",
                    ""id"": ""f932c505-a2f0-4b54-8386-c37ff02cb697"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4fa8fc32-f30f-45f5-8618-24419c84f85b"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c2b3574-d352-48ab-b23e-3b86d5ac18f8"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""905238af-9ba4-42ec-a15a-f3a350a097dc"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cf800ea-2d74-4786-8c98-3eab36fd5f84"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""NavigationUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c983fe9-1662-4144-b2d0-a8568112f43e"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""NavigationUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae58697d-e6bc-46bd-9a85-64745df8a8ef"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d414f70a-5205-4813-865c-0fa4c13f60c5"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84a5c060-f8fa-4220-bc7d-6fd57dcaef70"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d712925-0378-4a76-b944-802c923440c9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""NavigationDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6baa853b-ab56-40f4-b5b4-68fa59f68d17"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""NavigationDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02e7b4fa-ee03-4eb9-bcc5-0012df676f68"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9ac60cb-2f43-44ce-843f-8ff4c6090485"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27a2b5d4-4709-44c6-ab08-1bb18c5df1e7"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa87affb-e1a6-4c39-8b6b-75e4c7b96cdd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""NavigationLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7165ea0-d06f-4d17-9c02-3169fcdd7b72"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""NavigationLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc48e49f-f8b9-423e-abe7-1bf70c9c66e1"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9843e16a-6824-4dad-aa22-c31c348febf9"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigationRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67ab344b-06bb-499b-99e3-c09e82cf1416"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigationRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e4efd0a-7c58-4f64-9b69-87de227959dc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigationRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52799830-28cd-4846-bc89-9f6f24b5063f"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""NavigationRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9438a2ca-c2f6-4ddd-8ad3-d7b42e742c83"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationPrevious"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab219209-f69c-479b-b9a5-6e7cfb08a95c"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigationPrevious"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13b9194e-5a64-4413-bcf0-246339f3e115"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0899f236-03c5-4a5a-a17f-e882c14ac155"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02273aba-818f-4de8-981b-e65a8ad6d8c0"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""NavigationNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf8c031c-d2c7-4e5a-a17b-5bbaffa39809"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""NavigationNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f580a65-5d13-4f8f-8477-df5b0720e55e"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationTab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb286ce9-bcb3-49cd-8e87-33fb4a00098d"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""NavigationTab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ed143b5-2372-446f-bf8d-6b39f61e35ed"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationRightBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54d1eb7f-0038-4d4d-9468-aa75f3df0cb2"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationRightBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""815eda4a-80a0-4272-b6e3-b8410351660b"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""NavigationRightBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1ddfc72-00b9-4f1f-87ed-5a1c134e193b"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationLeftBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7771e832-7c2d-4fda-9b6c-30299797db19"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigationLeftBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2359bd86-4fa2-450a-b1a9-71ca6cc48647"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigationLeftBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""816ee135-515b-4987-8e26-0785301f6ab5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c53b8d2-7c32-49ca-9e54-f231a445c9e5"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3617d17-a730-4aeb-b066-3fc62dd72725"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""846b6fb0-89ea-4529-9fca-5ff35a4b88c7"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14360594-03c0-4c7e-ac57-4e3e82a0d72c"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07857805-0e20-48a6-9b0e-6f2d639699e4"",
                    ""path"": ""<Mouse>/forwardButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b46f1c9-1010-47ba-9f14-40250bd3525c"",
                    ""path"": ""<Mouse>/{Forward}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigationNextMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f74511ea-cfa9-4879-bc07-a09278077d78"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigationPreviousMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99028857-6fc2-4003-bb39-5dccfc3d361e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigationLeftMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""KBM"",
            ""bindingGroup"": ""KBM"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Vehicle
        m_Vehicle = asset.FindActionMap("Vehicle", throwIfNotFound: true);
        m_Vehicle_Forward = m_Vehicle.FindAction("Forward", throwIfNotFound: true);
        m_Vehicle_Reverse = m_Vehicle.FindAction("Reverse", throwIfNotFound: true);
        m_Vehicle_Steering = m_Vehicle.FindAction("Steering", throwIfNotFound: true);
        m_Vehicle_Handbrake = m_Vehicle.FindAction("Handbrake", throwIfNotFound: true);
        m_Vehicle_WeaponAim = m_Vehicle.FindAction("WeaponAim", throwIfNotFound: true);
        m_Vehicle_Boost = m_Vehicle.FindAction("Boost", throwIfNotFound: true);
        m_Vehicle_Pause = m_Vehicle.FindAction("Pause", throwIfNotFound: true);
        m_Vehicle_SpecialAction = m_Vehicle.FindAction("SpecialAction", throwIfNotFound: true);
        m_Vehicle_AbsoluteControl = m_Vehicle.FindAction("AbsoluteControl", throwIfNotFound: true);
        m_Vehicle_ToggleAutoAim = m_Vehicle.FindAction("ToggleAutoAim", throwIfNotFound: true);
        m_Vehicle_AnyButton = m_Vehicle.FindAction("AnyButton", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_NavigationUp = m_UI.FindAction("NavigationUp", throwIfNotFound: true);
        m_UI_NavigationDown = m_UI.FindAction("NavigationDown", throwIfNotFound: true);
        m_UI_NavigationLeft = m_UI.FindAction("NavigationLeft", throwIfNotFound: true);
        m_UI_NavigationRight = m_UI.FindAction("NavigationRight", throwIfNotFound: true);
        m_UI_NavigationPrevious = m_UI.FindAction("NavigationPrevious", throwIfNotFound: true);
        m_UI_NavigationNext = m_UI.FindAction("NavigationNext", throwIfNotFound: true);
        m_UI_NavigationTab = m_UI.FindAction("NavigationTab", throwIfNotFound: true);
        m_UI_NavigationRightBumper = m_UI.FindAction("NavigationRightBumper", throwIfNotFound: true);
        m_UI_NavigationLeftBumper = m_UI.FindAction("NavigationLeftBumper", throwIfNotFound: true);
        m_UI_MouseAction = m_UI.FindAction("MouseAction", throwIfNotFound: true);
        m_UI_NavigationNextMouse = m_UI.FindAction("NavigationNextMouse", throwIfNotFound: true);
        m_UI_NavigationPreviousMouse = m_UI.FindAction("NavigationPreviousMouse", throwIfNotFound: true);
        m_UI_NavigationLeftMouse = m_UI.FindAction("NavigationLeftMouse", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Vehicle
    private readonly InputActionMap m_Vehicle;
    private List<IVehicleActions> m_VehicleActionsCallbackInterfaces = new List<IVehicleActions>();
    private readonly InputAction m_Vehicle_Forward;
    private readonly InputAction m_Vehicle_Reverse;
    private readonly InputAction m_Vehicle_Steering;
    private readonly InputAction m_Vehicle_Handbrake;
    private readonly InputAction m_Vehicle_WeaponAim;
    private readonly InputAction m_Vehicle_Boost;
    private readonly InputAction m_Vehicle_Pause;
    private readonly InputAction m_Vehicle_SpecialAction;
    private readonly InputAction m_Vehicle_AbsoluteControl;
    private readonly InputAction m_Vehicle_ToggleAutoAim;
    private readonly InputAction m_Vehicle_AnyButton;
    public struct VehicleActions
    {
        private @PlayerInputActions m_Wrapper;
        public VehicleActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Forward => m_Wrapper.m_Vehicle_Forward;
        public InputAction @Reverse => m_Wrapper.m_Vehicle_Reverse;
        public InputAction @Steering => m_Wrapper.m_Vehicle_Steering;
        public InputAction @Handbrake => m_Wrapper.m_Vehicle_Handbrake;
        public InputAction @WeaponAim => m_Wrapper.m_Vehicle_WeaponAim;
        public InputAction @Boost => m_Wrapper.m_Vehicle_Boost;
        public InputAction @Pause => m_Wrapper.m_Vehicle_Pause;
        public InputAction @SpecialAction => m_Wrapper.m_Vehicle_SpecialAction;
        public InputAction @AbsoluteControl => m_Wrapper.m_Vehicle_AbsoluteControl;
        public InputAction @ToggleAutoAim => m_Wrapper.m_Vehicle_ToggleAutoAim;
        public InputAction @AnyButton => m_Wrapper.m_Vehicle_AnyButton;
        public InputActionMap Get() { return m_Wrapper.m_Vehicle; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VehicleActions set) { return set.Get(); }
        public void AddCallbacks(IVehicleActions instance)
        {
            if (instance == null || m_Wrapper.m_VehicleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VehicleActionsCallbackInterfaces.Add(instance);
            @Forward.started += instance.OnForward;
            @Forward.performed += instance.OnForward;
            @Forward.canceled += instance.OnForward;
            @Reverse.started += instance.OnReverse;
            @Reverse.performed += instance.OnReverse;
            @Reverse.canceled += instance.OnReverse;
            @Steering.started += instance.OnSteering;
            @Steering.performed += instance.OnSteering;
            @Steering.canceled += instance.OnSteering;
            @Handbrake.started += instance.OnHandbrake;
            @Handbrake.performed += instance.OnHandbrake;
            @Handbrake.canceled += instance.OnHandbrake;
            @WeaponAim.started += instance.OnWeaponAim;
            @WeaponAim.performed += instance.OnWeaponAim;
            @WeaponAim.canceled += instance.OnWeaponAim;
            @Boost.started += instance.OnBoost;
            @Boost.performed += instance.OnBoost;
            @Boost.canceled += instance.OnBoost;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @SpecialAction.started += instance.OnSpecialAction;
            @SpecialAction.performed += instance.OnSpecialAction;
            @SpecialAction.canceled += instance.OnSpecialAction;
            @AbsoluteControl.started += instance.OnAbsoluteControl;
            @AbsoluteControl.performed += instance.OnAbsoluteControl;
            @AbsoluteControl.canceled += instance.OnAbsoluteControl;
            @ToggleAutoAim.started += instance.OnToggleAutoAim;
            @ToggleAutoAim.performed += instance.OnToggleAutoAim;
            @ToggleAutoAim.canceled += instance.OnToggleAutoAim;
            @AnyButton.started += instance.OnAnyButton;
            @AnyButton.performed += instance.OnAnyButton;
            @AnyButton.canceled += instance.OnAnyButton;
        }

        private void UnregisterCallbacks(IVehicleActions instance)
        {
            @Forward.started -= instance.OnForward;
            @Forward.performed -= instance.OnForward;
            @Forward.canceled -= instance.OnForward;
            @Reverse.started -= instance.OnReverse;
            @Reverse.performed -= instance.OnReverse;
            @Reverse.canceled -= instance.OnReverse;
            @Steering.started -= instance.OnSteering;
            @Steering.performed -= instance.OnSteering;
            @Steering.canceled -= instance.OnSteering;
            @Handbrake.started -= instance.OnHandbrake;
            @Handbrake.performed -= instance.OnHandbrake;
            @Handbrake.canceled -= instance.OnHandbrake;
            @WeaponAim.started -= instance.OnWeaponAim;
            @WeaponAim.performed -= instance.OnWeaponAim;
            @WeaponAim.canceled -= instance.OnWeaponAim;
            @Boost.started -= instance.OnBoost;
            @Boost.performed -= instance.OnBoost;
            @Boost.canceled -= instance.OnBoost;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @SpecialAction.started -= instance.OnSpecialAction;
            @SpecialAction.performed -= instance.OnSpecialAction;
            @SpecialAction.canceled -= instance.OnSpecialAction;
            @AbsoluteControl.started -= instance.OnAbsoluteControl;
            @AbsoluteControl.performed -= instance.OnAbsoluteControl;
            @AbsoluteControl.canceled -= instance.OnAbsoluteControl;
            @ToggleAutoAim.started -= instance.OnToggleAutoAim;
            @ToggleAutoAim.performed -= instance.OnToggleAutoAim;
            @ToggleAutoAim.canceled -= instance.OnToggleAutoAim;
            @AnyButton.started -= instance.OnAnyButton;
            @AnyButton.performed -= instance.OnAnyButton;
            @AnyButton.canceled -= instance.OnAnyButton;
        }

        public void RemoveCallbacks(IVehicleActions instance)
        {
            if (m_Wrapper.m_VehicleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IVehicleActions instance)
        {
            foreach (var item in m_Wrapper.m_VehicleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VehicleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public VehicleActions @Vehicle => new VehicleActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_NavigationUp;
    private readonly InputAction m_UI_NavigationDown;
    private readonly InputAction m_UI_NavigationLeft;
    private readonly InputAction m_UI_NavigationRight;
    private readonly InputAction m_UI_NavigationPrevious;
    private readonly InputAction m_UI_NavigationNext;
    private readonly InputAction m_UI_NavigationTab;
    private readonly InputAction m_UI_NavigationRightBumper;
    private readonly InputAction m_UI_NavigationLeftBumper;
    private readonly InputAction m_UI_MouseAction;
    private readonly InputAction m_UI_NavigationNextMouse;
    private readonly InputAction m_UI_NavigationPreviousMouse;
    private readonly InputAction m_UI_NavigationLeftMouse;
    public struct UIActions
    {
        private @PlayerInputActions m_Wrapper;
        public UIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @NavigationUp => m_Wrapper.m_UI_NavigationUp;
        public InputAction @NavigationDown => m_Wrapper.m_UI_NavigationDown;
        public InputAction @NavigationLeft => m_Wrapper.m_UI_NavigationLeft;
        public InputAction @NavigationRight => m_Wrapper.m_UI_NavigationRight;
        public InputAction @NavigationPrevious => m_Wrapper.m_UI_NavigationPrevious;
        public InputAction @NavigationNext => m_Wrapper.m_UI_NavigationNext;
        public InputAction @NavigationTab => m_Wrapper.m_UI_NavigationTab;
        public InputAction @NavigationRightBumper => m_Wrapper.m_UI_NavigationRightBumper;
        public InputAction @NavigationLeftBumper => m_Wrapper.m_UI_NavigationLeftBumper;
        public InputAction @MouseAction => m_Wrapper.m_UI_MouseAction;
        public InputAction @NavigationNextMouse => m_Wrapper.m_UI_NavigationNextMouse;
        public InputAction @NavigationPreviousMouse => m_Wrapper.m_UI_NavigationPreviousMouse;
        public InputAction @NavigationLeftMouse => m_Wrapper.m_UI_NavigationLeftMouse;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @NavigationUp.started += instance.OnNavigationUp;
            @NavigationUp.performed += instance.OnNavigationUp;
            @NavigationUp.canceled += instance.OnNavigationUp;
            @NavigationDown.started += instance.OnNavigationDown;
            @NavigationDown.performed += instance.OnNavigationDown;
            @NavigationDown.canceled += instance.OnNavigationDown;
            @NavigationLeft.started += instance.OnNavigationLeft;
            @NavigationLeft.performed += instance.OnNavigationLeft;
            @NavigationLeft.canceled += instance.OnNavigationLeft;
            @NavigationRight.started += instance.OnNavigationRight;
            @NavigationRight.performed += instance.OnNavigationRight;
            @NavigationRight.canceled += instance.OnNavigationRight;
            @NavigationPrevious.started += instance.OnNavigationPrevious;
            @NavigationPrevious.performed += instance.OnNavigationPrevious;
            @NavigationPrevious.canceled += instance.OnNavigationPrevious;
            @NavigationNext.started += instance.OnNavigationNext;
            @NavigationNext.performed += instance.OnNavigationNext;
            @NavigationNext.canceled += instance.OnNavigationNext;
            @NavigationTab.started += instance.OnNavigationTab;
            @NavigationTab.performed += instance.OnNavigationTab;
            @NavigationTab.canceled += instance.OnNavigationTab;
            @NavigationRightBumper.started += instance.OnNavigationRightBumper;
            @NavigationRightBumper.performed += instance.OnNavigationRightBumper;
            @NavigationRightBumper.canceled += instance.OnNavigationRightBumper;
            @NavigationLeftBumper.started += instance.OnNavigationLeftBumper;
            @NavigationLeftBumper.performed += instance.OnNavigationLeftBumper;
            @NavigationLeftBumper.canceled += instance.OnNavigationLeftBumper;
            @MouseAction.started += instance.OnMouseAction;
            @MouseAction.performed += instance.OnMouseAction;
            @MouseAction.canceled += instance.OnMouseAction;
            @NavigationNextMouse.started += instance.OnNavigationNextMouse;
            @NavigationNextMouse.performed += instance.OnNavigationNextMouse;
            @NavigationNextMouse.canceled += instance.OnNavigationNextMouse;
            @NavigationPreviousMouse.started += instance.OnNavigationPreviousMouse;
            @NavigationPreviousMouse.performed += instance.OnNavigationPreviousMouse;
            @NavigationPreviousMouse.canceled += instance.OnNavigationPreviousMouse;
            @NavigationLeftMouse.started += instance.OnNavigationLeftMouse;
            @NavigationLeftMouse.performed += instance.OnNavigationLeftMouse;
            @NavigationLeftMouse.canceled += instance.OnNavigationLeftMouse;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @NavigationUp.started -= instance.OnNavigationUp;
            @NavigationUp.performed -= instance.OnNavigationUp;
            @NavigationUp.canceled -= instance.OnNavigationUp;
            @NavigationDown.started -= instance.OnNavigationDown;
            @NavigationDown.performed -= instance.OnNavigationDown;
            @NavigationDown.canceled -= instance.OnNavigationDown;
            @NavigationLeft.started -= instance.OnNavigationLeft;
            @NavigationLeft.performed -= instance.OnNavigationLeft;
            @NavigationLeft.canceled -= instance.OnNavigationLeft;
            @NavigationRight.started -= instance.OnNavigationRight;
            @NavigationRight.performed -= instance.OnNavigationRight;
            @NavigationRight.canceled -= instance.OnNavigationRight;
            @NavigationPrevious.started -= instance.OnNavigationPrevious;
            @NavigationPrevious.performed -= instance.OnNavigationPrevious;
            @NavigationPrevious.canceled -= instance.OnNavigationPrevious;
            @NavigationNext.started -= instance.OnNavigationNext;
            @NavigationNext.performed -= instance.OnNavigationNext;
            @NavigationNext.canceled -= instance.OnNavigationNext;
            @NavigationTab.started -= instance.OnNavigationTab;
            @NavigationTab.performed -= instance.OnNavigationTab;
            @NavigationTab.canceled -= instance.OnNavigationTab;
            @NavigationRightBumper.started -= instance.OnNavigationRightBumper;
            @NavigationRightBumper.performed -= instance.OnNavigationRightBumper;
            @NavigationRightBumper.canceled -= instance.OnNavigationRightBumper;
            @NavigationLeftBumper.started -= instance.OnNavigationLeftBumper;
            @NavigationLeftBumper.performed -= instance.OnNavigationLeftBumper;
            @NavigationLeftBumper.canceled -= instance.OnNavigationLeftBumper;
            @MouseAction.started -= instance.OnMouseAction;
            @MouseAction.performed -= instance.OnMouseAction;
            @MouseAction.canceled -= instance.OnMouseAction;
            @NavigationNextMouse.started -= instance.OnNavigationNextMouse;
            @NavigationNextMouse.performed -= instance.OnNavigationNextMouse;
            @NavigationNextMouse.canceled -= instance.OnNavigationNextMouse;
            @NavigationPreviousMouse.started -= instance.OnNavigationPreviousMouse;
            @NavigationPreviousMouse.performed -= instance.OnNavigationPreviousMouse;
            @NavigationPreviousMouse.canceled -= instance.OnNavigationPreviousMouse;
            @NavigationLeftMouse.started -= instance.OnNavigationLeftMouse;
            @NavigationLeftMouse.performed -= instance.OnNavigationLeftMouse;
            @NavigationLeftMouse.canceled -= instance.OnNavigationLeftMouse;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_KBMSchemeIndex = -1;
    public InputControlScheme KBMScheme
    {
        get
        {
            if (m_KBMSchemeIndex == -1) m_KBMSchemeIndex = asset.FindControlSchemeIndex("KBM");
            return asset.controlSchemes[m_KBMSchemeIndex];
        }
    }
    public interface IVehicleActions
    {
        void OnForward(InputAction.CallbackContext context);
        void OnReverse(InputAction.CallbackContext context);
        void OnSteering(InputAction.CallbackContext context);
        void OnHandbrake(InputAction.CallbackContext context);
        void OnWeaponAim(InputAction.CallbackContext context);
        void OnBoost(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnSpecialAction(InputAction.CallbackContext context);
        void OnAbsoluteControl(InputAction.CallbackContext context);
        void OnToggleAutoAim(InputAction.CallbackContext context);
        void OnAnyButton(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnNavigationUp(InputAction.CallbackContext context);
        void OnNavigationDown(InputAction.CallbackContext context);
        void OnNavigationLeft(InputAction.CallbackContext context);
        void OnNavigationRight(InputAction.CallbackContext context);
        void OnNavigationPrevious(InputAction.CallbackContext context);
        void OnNavigationNext(InputAction.CallbackContext context);
        void OnNavigationTab(InputAction.CallbackContext context);
        void OnNavigationRightBumper(InputAction.CallbackContext context);
        void OnNavigationLeftBumper(InputAction.CallbackContext context);
        void OnMouseAction(InputAction.CallbackContext context);
        void OnNavigationNextMouse(InputAction.CallbackContext context);
        void OnNavigationPreviousMouse(InputAction.CallbackContext context);
        void OnNavigationLeftMouse(InputAction.CallbackContext context);
    }
}
